export const enum ConsumerConstant {
	Consumer = 'Consumer',
	UserName = 'Username',
	Custom_Id = 'Custom ID',
	Tags = 'Tags',
	Created_At = "Created At",
	Action = 'Action',
	Reload = 'Reload',
	New = 'New',
	Export = 'Export',
	Download = 'Download',
	Import = 'Import',
	Save = 'Save',
	Add = 'Add',
	Edit = 'Edit',
	Delete = 'Delete',
	Remove = 'Remove',
	Copy = 'Copy',
	CSV = 'CSV',
	Excel = 'Excel',
	PDF = 'PDF',
	MessageAdd = 'Add New Consumer',
	MessageImport = 'Import Consumer',
	MessageCopy = 'Are you sure to copy this consumer?',
	MessageEdit = 'Edit Consumer',
	MessageDelete = 'Are you sure to delete this consumer?',
	MessageValidationEmpty = "At least one of these fields must be non-empty: 'custom_id', 'username'"
}