import { OnInit, EventEmitter, OnChanges } from "@angular/core";
import { ActivatedRoute, Router } from '@angular/router';
import { DefaultLayoutService } from './layout.service';
import { MenuService } from '../shared/services/menu.service';
import { ExtendedMainMenuGroup, MenuTab, MenuItem, Breadcrumb } from '../shared/models/base.model';
import { ActionService } from '../shared/services/action.service';
import { AggregatorService } from '../shared/services/aggregator.service';
export declare class DefaultSidebarComponent implements OnInit, OnChanges {
    workspaceLayoutService: DefaultLayoutService;
    protected route: ActivatedRoute;
    protected router: Router;
    protected menuService: MenuService;
    protected actionService: ActionService;
    protected aggregatorService: AggregatorService;
    menuTabs: MenuTab[];
    navigateTo: (menu: string, router: Router) => void;
    set: (role: string) => MenuItem;
    menuType: string;
    setActive: boolean;
    change: EventEmitter<Breadcrumb[]>;
    currentUrl: string;
    menuItems: ExtendedMainMenuGroup[];
    isCollapsedSideBar: string;
    collapsedItems: ExtendedMainMenuGroup[];
    isSupplier: boolean;
    tabs: {
        name: string;
        menu: string;
        subName: string;
    }[];
    carouselTile: any;
    isPageLoad: boolean;
    isMobile: boolean;
    clicked: boolean;
    constructor(workspaceLayoutService: DefaultLayoutService, route: ActivatedRoute, router: Router, menuService: MenuService, actionService: ActionService, aggregatorService: AggregatorService);
    ngOnChanges(): void;
    ngOnInit(): void;
    toggleMenu(): void;
    toggleOpenedSidebar(): void;
    loadMenu(menu: string): void;
    selectItem(item: any): void;
    private selectMenu;
}
